# Generated by Django 4.2 on 2023-04-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Heading',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
